
# Generated by Django 3.2.2 on 2021-05-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ratingmovie',
            table='rating_movies',
        ),
    ]
