# Generated by Django 3.2.2 on 2021-05-12 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='comment_id',
            field=models.ManyToManyField(related_name='user', through='movies.Comment', to='users.User'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director_id',
            field=models.ManyToManyField(through='movies.Movie_Director', to='movies.Director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre_id',
            field=models.ManyToManyField(through='movies.Movie_Genre', to='movies.Genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='provider_id',
            field=models.ManyToManyField(through='movies.Movie_Provider', to='movies.Provider'),
        ),
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.comment'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
