# Generated by Django 3.2.2 on 2021-05-12 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='moviegenre',
            table='movie_genres',
        ),
    ]
